---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  # Customize in your overlay.
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 1Gi
