apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vmtest
spec:
  dataVolumeTemplates:
    - metadata:
        labels:
          appName: vmtest
        name: vmtest-volume
      spec:
        sourceRef:
          kind: DataSource
          name: rhel8
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
          storageClassName: ocs-storagecluster-ceph-rbd
  instancetype:
    name: u1.medium
  preference:
    name: rhel.8
  running: true
  template:
    metadata:
      labels:
        network.kubevirt.io/headlessService: headless
    spec:
      domain:
        devices:
          autoattachPodInterface: false
          disks: []
          interfaces:
            - masquerade: {}
              name: default
      networks:
        - name: default
          pod: {}
      subdomain: headless
      volumes:
        - dataVolume:
            name: vmtest-volume
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              user: rhel
          name: cloudinitdisk

